/*
Navicat MySQL Data Transfer

Source Server         : 172.16.134.31
Source Server Version : 50543
Source Host           : 172.16.134.31:3306
Source Database       : mydatabase

Target Server Type    : MYSQL
Target Server Version : 50543
File Encoding         : 65001

Date: 2018-06-08 17:36:49
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for FUND
-- ----------------------------
DROP TABLE IF EXISTS `FUND`;
CREATE TABLE `FUND` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FUND_CODE` varchar(255) DEFAULT NULL,
  `FUND_NAME` varchar(255) DEFAULT NULL,
  `FUND_UNITVALUE` float(255,5) DEFAULT NULL,
  `FUND_TOTALVALUE` float(255,5) DEFAULT NULL,
  `FUND_DALIYINCREASE` float(255,5) DEFAULT NULL,
  `FUND_LASTWEEK` float(255,5) DEFAULT NULL,
  `FUND_LASTMONTH` float(255,5) DEFAULT NULL,
  `FUND_LAST3MONTH` float(255,5) DEFAULT NULL,
  `FUND_LAST6MONTH` float(255,5) DEFAULT NULL,
  `FUND_LASTYEAR` float(255,5) DEFAULT NULL,
  `FUND_LAST2YEAR` float(255,5) DEFAULT NULL,
  `FUND_LAST3YEAR` float(255,5) DEFAULT NULL,
  `FUND_LASTTHISYEAR` float(255,5) DEFAULT NULL,
  `FUND_SINCECONSTRUCT` float(255,5) DEFAULT NULL,
  `FUND_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=16329 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for FUND_STOCK
-- ----------------------------
DROP TABLE IF EXISTS `FUND_STOCK`;
CREATE TABLE `FUND_STOCK` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FUND_CODE` varchar(255) DEFAULT NULL,
  `FUND_NAME` varchar(255) DEFAULT NULL,
  `STOCK_CODE` varchar(255) DEFAULT NULL,
  `STOCK_NAME` varchar(255) DEFAULT NULL,
  `HowMany` float(11,5) DEFAULT NULL,
  `INCREASE` float(11,5) DEFAULT NULL,
  `UPDATEDATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=109494 DEFAULT CHARSET=utf8;

-- ----------------------------
-- View structure for FUND_LAST2YEAR_TOP100
-- ----------------------------
DROP VIEW IF EXISTS `FUND_LAST2YEAR_TOP100`;
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql`@`%` SQL SECURITY DEFINER VIEW `FUND_LAST2YEAR_TOP100` AS select `T`.`ID` AS `ID`,`T`.`FUND_CODE` AS `FUND_CODE`,`T`.`FUND_NAME` AS `FUND_NAME`,`T`.`FUND_UNITVALUE` AS `FUND_UNITVALUE`,`T`.`FUND_TOTALVALUE` AS `FUND_TOTALVALUE`,`T`.`FUND_DALIYINCREASE` AS `FUND_DALIYINCREASE`,`T`.`FUND_LASTWEEK` AS `FUND_LASTWEEK`,`T`.`FUND_LASTMONTH` AS `FUND_LASTMONTH`,`T`.`FUND_LAST3MONTH` AS `FUND_LAST3MONTH`,`T`.`FUND_LAST6MONTH` AS `FUND_LAST6MONTH`,`T`.`FUND_LASTYEAR` AS `FUND_LASTYEAR`,`T`.`FUND_LAST2YEAR` AS `FUND_LAST2YEAR`,`T`.`FUND_LAST3YEAR` AS `FUND_LAST3YEAR`,`T`.`FUND_LASTTHISYEAR` AS `FUND_LASTTHISYEAR`,`T`.`FUND_SINCECONSTRUCT` AS `FUND_SINCECONSTRUCT`,`T`.`FUND_DATE` AS `FUND_DATE` from `FUND` `T` order by `T`.`FUND_LAST2YEAR` desc limit 100 ;

-- ----------------------------
-- View structure for FUND_LAST3MONTH_TOP100
-- ----------------------------
DROP VIEW IF EXISTS `FUND_LAST3MONTH_TOP100`;
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql`@`%` SQL SECURITY DEFINER VIEW `FUND_LAST3MONTH_TOP100` AS select `T`.`ID` AS `ID`,`T`.`FUND_CODE` AS `FUND_CODE`,`T`.`FUND_NAME` AS `FUND_NAME`,`T`.`FUND_UNITVALUE` AS `FUND_UNITVALUE`,`T`.`FUND_TOTALVALUE` AS `FUND_TOTALVALUE`,`T`.`FUND_DALIYINCREASE` AS `FUND_DALIYINCREASE`,`T`.`FUND_LASTWEEK` AS `FUND_LASTWEEK`,`T`.`FUND_LASTMONTH` AS `FUND_LASTMONTH`,`T`.`FUND_LAST3MONTH` AS `FUND_LAST3MONTH`,`T`.`FUND_LAST6MONTH` AS `FUND_LAST6MONTH`,`T`.`FUND_LASTYEAR` AS `FUND_LASTYEAR`,`T`.`FUND_LAST2YEAR` AS `FUND_LAST2YEAR`,`T`.`FUND_LAST3YEAR` AS `FUND_LAST3YEAR`,`T`.`FUND_LASTTHISYEAR` AS `FUND_LASTTHISYEAR`,`T`.`FUND_SINCECONSTRUCT` AS `FUND_SINCECONSTRUCT`,`T`.`FUND_DATE` AS `FUND_DATE` from `FUND` `T` order by `T`.`FUND_LAST3MONTH` desc limit 100 ;

-- ----------------------------
-- View structure for FUND_LAST3YEAR_TOP100
-- ----------------------------
DROP VIEW IF EXISTS `FUND_LAST3YEAR_TOP100`;
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql`@`%` SQL SECURITY DEFINER VIEW `FUND_LAST3YEAR_TOP100` AS select `T`.`ID` AS `ID`,`T`.`FUND_CODE` AS `FUND_CODE`,`T`.`FUND_NAME` AS `FUND_NAME`,`T`.`FUND_UNITVALUE` AS `FUND_UNITVALUE`,`T`.`FUND_TOTALVALUE` AS `FUND_TOTALVALUE`,`T`.`FUND_DALIYINCREASE` AS `FUND_DALIYINCREASE`,`T`.`FUND_LASTWEEK` AS `FUND_LASTWEEK`,`T`.`FUND_LASTMONTH` AS `FUND_LASTMONTH`,`T`.`FUND_LAST3MONTH` AS `FUND_LAST3MONTH`,`T`.`FUND_LAST6MONTH` AS `FUND_LAST6MONTH`,`T`.`FUND_LASTYEAR` AS `FUND_LASTYEAR`,`T`.`FUND_LAST2YEAR` AS `FUND_LAST2YEAR`,`T`.`FUND_LAST3YEAR` AS `FUND_LAST3YEAR`,`T`.`FUND_LASTTHISYEAR` AS `FUND_LASTTHISYEAR`,`T`.`FUND_SINCECONSTRUCT` AS `FUND_SINCECONSTRUCT`,`T`.`FUND_DATE` AS `FUND_DATE` from `FUND` `T` order by `T`.`FUND_LAST3YEAR` desc limit 100 ;

-- ----------------------------
-- View structure for FUND_LAST6MONTH_TOP100
-- ----------------------------
DROP VIEW IF EXISTS `FUND_LAST6MONTH_TOP100`;
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql`@`%` SQL SECURITY DEFINER VIEW `FUND_LAST6MONTH_TOP100` AS select `T`.`ID` AS `ID`,`T`.`FUND_CODE` AS `FUND_CODE`,`T`.`FUND_NAME` AS `FUND_NAME`,`T`.`FUND_UNITVALUE` AS `FUND_UNITVALUE`,`T`.`FUND_TOTALVALUE` AS `FUND_TOTALVALUE`,`T`.`FUND_DALIYINCREASE` AS `FUND_DALIYINCREASE`,`T`.`FUND_LASTWEEK` AS `FUND_LASTWEEK`,`T`.`FUND_LASTMONTH` AS `FUND_LASTMONTH`,`T`.`FUND_LAST3MONTH` AS `FUND_LAST3MONTH`,`T`.`FUND_LAST6MONTH` AS `FUND_LAST6MONTH`,`T`.`FUND_LASTYEAR` AS `FUND_LASTYEAR`,`T`.`FUND_LAST2YEAR` AS `FUND_LAST2YEAR`,`T`.`FUND_LAST3YEAR` AS `FUND_LAST3YEAR`,`T`.`FUND_LASTTHISYEAR` AS `FUND_LASTTHISYEAR`,`T`.`FUND_SINCECONSTRUCT` AS `FUND_SINCECONSTRUCT`,`T`.`FUND_DATE` AS `FUND_DATE` from `FUND` `T` order by `T`.`FUND_LAST6MONTH` desc limit 100 ;

-- ----------------------------
-- View structure for FUND_LASTMONTH_TOP100
-- ----------------------------
DROP VIEW IF EXISTS `FUND_LASTMONTH_TOP100`;
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql`@`%` SQL SECURITY DEFINER VIEW `FUND_LASTMONTH_TOP100` AS select `T`.`ID` AS `ID`,`T`.`FUND_CODE` AS `FUND_CODE`,`T`.`FUND_NAME` AS `FUND_NAME`,`T`.`FUND_UNITVALUE` AS `FUND_UNITVALUE`,`T`.`FUND_TOTALVALUE` AS `FUND_TOTALVALUE`,`T`.`FUND_DALIYINCREASE` AS `FUND_DALIYINCREASE`,`T`.`FUND_LASTWEEK` AS `FUND_LASTWEEK`,`T`.`FUND_LASTMONTH` AS `FUND_LASTMONTH`,`T`.`FUND_LAST3MONTH` AS `FUND_LAST3MONTH`,`T`.`FUND_LAST6MONTH` AS `FUND_LAST6MONTH`,`T`.`FUND_LASTYEAR` AS `FUND_LASTYEAR`,`T`.`FUND_LAST2YEAR` AS `FUND_LAST2YEAR`,`T`.`FUND_LAST3YEAR` AS `FUND_LAST3YEAR`,`T`.`FUND_LASTTHISYEAR` AS `FUND_LASTTHISYEAR`,`T`.`FUND_SINCECONSTRUCT` AS `FUND_SINCECONSTRUCT`,`T`.`FUND_DATE` AS `FUND_DATE` from `FUND` `T` order by `T`.`FUND_LASTMONTH` desc limit 100 ;

-- ----------------------------
-- View structure for FUND_LASTWEEK_TOP100
-- ----------------------------
DROP VIEW IF EXISTS `FUND_LASTWEEK_TOP100`;
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql`@`%` SQL SECURITY DEFINER VIEW `FUND_LASTWEEK_TOP100` AS select `T`.`ID` AS `ID`,`T`.`FUND_CODE` AS `FUND_CODE`,`T`.`FUND_NAME` AS `FUND_NAME`,`T`.`FUND_UNITVALUE` AS `FUND_UNITVALUE`,`T`.`FUND_TOTALVALUE` AS `FUND_TOTALVALUE`,`T`.`FUND_DALIYINCREASE` AS `FUND_DALIYINCREASE`,`T`.`FUND_LASTWEEK` AS `FUND_LASTWEEK`,`T`.`FUND_LASTMONTH` AS `FUND_LASTMONTH`,`T`.`FUND_LAST3MONTH` AS `FUND_LAST3MONTH`,`T`.`FUND_LAST6MONTH` AS `FUND_LAST6MONTH`,`T`.`FUND_LASTYEAR` AS `FUND_LASTYEAR`,`T`.`FUND_LAST2YEAR` AS `FUND_LAST2YEAR`,`T`.`FUND_LAST3YEAR` AS `FUND_LAST3YEAR`,`T`.`FUND_LASTTHISYEAR` AS `FUND_LASTTHISYEAR`,`T`.`FUND_SINCECONSTRUCT` AS `FUND_SINCECONSTRUCT`,`T`.`FUND_DATE` AS `FUND_DATE` from `FUND` `T` order by `T`.`FUND_LASTWEEK` desc limit 100 ;

-- ----------------------------
-- View structure for FUND_LASTYEAR_TOP100
-- ----------------------------
DROP VIEW IF EXISTS `FUND_LASTYEAR_TOP100`;
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql`@`%` SQL SECURITY DEFINER VIEW `FUND_LASTYEAR_TOP100` AS select `T`.`ID` AS `ID`,`T`.`FUND_CODE` AS `FUND_CODE`,`T`.`FUND_NAME` AS `FUND_NAME`,`T`.`FUND_UNITVALUE` AS `FUND_UNITVALUE`,`T`.`FUND_TOTALVALUE` AS `FUND_TOTALVALUE`,`T`.`FUND_DALIYINCREASE` AS `FUND_DALIYINCREASE`,`T`.`FUND_LASTWEEK` AS `FUND_LASTWEEK`,`T`.`FUND_LASTMONTH` AS `FUND_LASTMONTH`,`T`.`FUND_LAST3MONTH` AS `FUND_LAST3MONTH`,`T`.`FUND_LAST6MONTH` AS `FUND_LAST6MONTH`,`T`.`FUND_LASTYEAR` AS `FUND_LASTYEAR`,`T`.`FUND_LAST2YEAR` AS `FUND_LAST2YEAR`,`T`.`FUND_LAST3YEAR` AS `FUND_LAST3YEAR`,`T`.`FUND_LASTTHISYEAR` AS `FUND_LASTTHISYEAR`,`T`.`FUND_SINCECONSTRUCT` AS `FUND_SINCECONSTRUCT`,`T`.`FUND_DATE` AS `FUND_DATE` from `FUND` `T` order by `T`.`FUND_LASTYEAR` desc limit 100 ;

-- ----------------------------
-- View structure for FUND_SINCECONSTRUCT_TOP100
-- ----------------------------
DROP VIEW IF EXISTS `FUND_SINCECONSTRUCT_TOP100`;
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql`@`%` SQL SECURITY DEFINER VIEW `FUND_SINCECONSTRUCT_TOP100` AS select `T`.`ID` AS `ID`,`T`.`FUND_CODE` AS `FUND_CODE`,`T`.`FUND_NAME` AS `FUND_NAME`,`T`.`FUND_UNITVALUE` AS `FUND_UNITVALUE`,`T`.`FUND_TOTALVALUE` AS `FUND_TOTALVALUE`,`T`.`FUND_DALIYINCREASE` AS `FUND_DALIYINCREASE`,`T`.`FUND_LASTWEEK` AS `FUND_LASTWEEK`,`T`.`FUND_LASTMONTH` AS `FUND_LASTMONTH`,`T`.`FUND_LAST3MONTH` AS `FUND_LAST3MONTH`,`T`.`FUND_LAST6MONTH` AS `FUND_LAST6MONTH`,`T`.`FUND_LASTYEAR` AS `FUND_LASTYEAR`,`T`.`FUND_LAST2YEAR` AS `FUND_LAST2YEAR`,`T`.`FUND_LAST3YEAR` AS `FUND_LAST3YEAR`,`T`.`FUND_LASTTHISYEAR` AS `FUND_LASTTHISYEAR`,`T`.`FUND_SINCECONSTRUCT` AS `FUND_SINCECONSTRUCT`,`T`.`FUND_DATE` AS `FUND_DATE` from `FUND` `T` order by `T`.`FUND_SINCECONSTRUCT` desc limit 100 ;

-- ----------------------------
-- View structure for FUND_STOCK数量
-- ----------------------------
DROP VIEW IF EXISTS `FUND_STOCK数量`;
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql`@`%` SQL SECURITY DEFINER VIEW `FUND_STOCK数量` AS select `T1`.`UPDATEDATE` AS `UPDATEDATE`,count(0) AS `COUNT(*)` from `FUND_STOCK` `T1` group by `T1`.`UPDATEDATE` ;

-- ----------------------------
-- View structure for FUND数量
-- ----------------------------
DROP VIEW IF EXISTS `FUND数量`;
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql`@`%` SQL SECURITY DEFINER VIEW `FUND数量` AS select `T`.`FUND_DATE` AS `FUND_DATE`,count(0) AS `COUNT(*)` from `FUND` `T` group by `T`.`FUND_DATE` ;

-- ----------------------------
-- View structure for 分析1
-- ----------------------------
DROP VIEW IF EXISTS `分析1`;
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql`@`%` SQL SECURITY DEFINER VIEW `分析1` AS select `fs`.`STOCK_CODE` AS `STOCK_CODE`,`fs`.`STOCK_NAME` AS `STOCK_NAME`,count(0) AS `count(*)`,sum(`fs`.`HowMany`) AS `sum(HowMany)` from `FUND_STOCK` `fs` where (`fs`.`UPDATEDATE` = '2018-06-05 00:00:00') group by `fs`.`STOCK_CODE` order by count(0) desc ;

-- ----------------------------
-- View structure for 分析2
-- ----------------------------
DROP VIEW IF EXISTS `分析2`;
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql`@`%` SQL SECURITY DEFINER VIEW `分析2` AS select `FS1`.`FUND_CODE` AS `FUND_CODE`,`FS1`.`FUND_NAME` AS `FUND_NAME`,`FS1`.`STOCK_CODE` AS `STOCK_CODE`,`FS1`.`STOCK_NAME` AS `STOCK_NAME`,`FS1`.`ID` AS `id`,`FS1`.`HowMany` AS `HowMany`,`FS1`.`INCREASE` AS `INCREASE`,`FS2`.`ID` AS `id2`,`FS2`.`HowMany` AS `HowMany1`,`FS2`.`INCREASE` AS `INCREASE1` from (`FUND_STOCK` `FS1` join `FUND_STOCK` `FS2`) where ((`FS1`.`UPDATEDATE` = '2018-06-05 00:00:00') and (`FS2`.`UPDATEDATE` = '2018-06-06 00:00:00') and (`FS1`.`FUND_CODE` = `FS2`.`FUND_CODE`) and (`FS1`.`STOCK_CODE` = `FS2`.`STOCK_CODE`) and `FS1`.`FUND_CODE` in (select `FUND_LASTMONTH_TOP100`.`FUND_CODE` from `FUND_LASTMONTH_TOP100`) and `FS2`.`FUND_CODE` in (select `FUND_LASTMONTH_TOP100`.`FUND_CODE` from `FUND_LASTMONTH_TOP100`)) order by `FS1`.`FUND_CODE` ;

-- ----------------------------
-- View structure for 分析3
-- ----------------------------
DROP VIEW IF EXISTS `分析3`;
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql`@`%` SQL SECURITY DEFINER VIEW `分析3` AS select `T1`.`FUND_CODE` AS `FUND_CODE`,`T1`.`FUND_NAME` AS `FUND_NAME`,`T1`.`STOCK_CODE` AS `STOCK_CODE`,`T1`.`STOCK_NAME` AS `STOCK_NAME`,`T1`.`HowMany` AS `HowMany`,`T1`.`INCREASE` AS `INCREASE`,`T2`.`HowMany` AS `HowMany1`,`T2`.`INCREASE` AS `INCREASE1`,`T1`.`ID` AS `id`,`T2`.`ID` AS `id1` from (`FUND_STOCK` `T1` left join `FUND_STOCK` `T2` on(((`T1`.`FUND_CODE` = `T2`.`FUND_CODE`) and (`T1`.`STOCK_CODE` = `T2`.`STOCK_CODE`) and (`T2`.`UPDATEDATE` = '2018-06-05 00:00:00') and (`T1`.`HowMany` <> `T2`.`HowMany`)))) where (`T1`.`FUND_CODE` in (select `FUND_LAST6MONTH_TOP100`.`FUND_CODE` from `FUND_LAST6MONTH_TOP100`) and (`T1`.`UPDATEDATE` = '2018-06-07 00:00:00')) ;

-- ----------------------------
-- View structure for 分析4
-- ----------------------------
DROP VIEW IF EXISTS `分析4`;
CREATE ALGORITHM=UNDEFINED DEFINER=`mysql`@`%` SQL SECURITY DEFINER VIEW `分析4` AS select `fs`.`STOCK_CODE` AS `STOCK_CODE`,`fs`.`STOCK_NAME` AS `STOCK_NAME`,count(0) AS `count(*)`,sum(`fs`.`HowMany`) AS `sum(HowMany)` from `FUND_STOCK` `fs` where (`fs`.`UPDATEDATE` = '2018-06-08 00:00:00') group by `fs`.`STOCK_CODE` order by count(0) desc ;
