export QINIU_ACCESS_KEY="5zICAtLUtlGbbMfDB2ucQ9OxyO3zwQTG6I5do11P"
export QINIU_SECRET_KEY="c2mM0jRfxm9hYDdsbeFqBR4akbMqG8n6TpIl4mE7"
export QINIU_TEST_BUCKET="xhu218"
export QINIU_TEST_DOMAIN="<BUCKEY DOMAIN>"
